name: conditional_flex_fit
description: Wrap a widget conditionally with a Flexible and a FittedBox
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^3.1.0
dependencies:
  flutter:
    sdk: flutter
