name: fudeo_hackaton
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.3
  favourites_repository:
    path: packages/favourites_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fudeo_api:
    path: packages/fudeo_api
  job_offer_repository:
    path: packages/job_offer_repository
  rxdart: ^0.27.4
  social_share_repository:
    path: packages/social_share_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
